name: Build Windows Custom Client

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: 'Tag name for release'
        required: false
        default: 'custom-build'

jobs:
  build-windows:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag }}
